spring:
  application:
    name: gpt-game

yandex:
  cloud:
    api-key: ${YANDEX_API_KEY}
    folder-id: ${YANDEX_FOLDER_ID}
    api-url: ${YANDEX_API_URL}
    model: ${GPT_MODEL}
    model-version: ${GPT_MODEL_VERSION}
    gpt:
      temperature: ${GPT_TEMPERATURE} # Креативность ответов
      max-tokens: ${GPT_MAX_TOKENS}

rest:
  http:
    connect-timeout: 30000 # 30 секунд
    read-timeout: 60000 # 60 секунд
