# !!! Файл попадает в JAR, не делитесь сборкой для исключения утечки данных !!!
# !!! Альтернатива - используйте переменные среды вашей ОС (ENV) или передавайте через параметры запуска в IDE !!!

YANDEX_API_KEY: fix_me
YANDEX_FOLDER_ID: fix_me