spring:
  application:
    name: gpt-game
yandex:
  cloud:
    api-key: ${YANDEX_API_KEY}
    folder-id: ${YANDEX_FOLDER_ID}
    api-url: ${YANDEX_API_URL}
    gpt:
      model: ${GPT_MODEL}
      temperature: ${GPT_TEMPERATURE}       # Креативность ответов
      max-tokens: ${GPT_MAX_TOKENS}
